"""Public Gate 6 Evidence Materialization API."""

from .evidence_materialization_canonicalization import (
    canonicalize_evidence_collection_identity,
    canonicalize_evidence_eligibility_snapshot,
    canonicalize_traceable_evidence_identity,
    derive_evidence_collection_id,
    derive_evidence_eligibility_snapshot_digest,
    derive_traceable_evidence_id,
)
from .evidence_materialization_contract import (
    EVIDENCE_COLLECTION_CONTRACT_VERSION,
    EVIDENCE_COLLECTION_IDENTITY_CANONICALIZATION_VERSION,
    EVIDENCE_COLLECTION_IDENTITY_FIELD_ORDER,
    EVIDENCE_COLLECTION_ID_PREFIX,
    EVIDENCE_COLLECTION_FIELD_ORDER,
    EVIDENCE_ELIGIBILITY_FIELD_ORDER,
    EVIDENCE_ELIGIBILITY_SNAPSHOT_CANONICALIZATION_VERSION,
    EVIDENCE_ELIGIBILITY_SNAPSHOT_CONTRACT_VERSION,
    EVIDENCE_MATERIALIZATION_ISSUE_FIELD_ORDER,
    EVIDENCE_MATERIALIZATION_RESULT_CONTRACT_VERSION,
    EVIDENCE_MATERIALIZATION_RESULT_FIELD_ORDER,
    TRACEABLE_EVIDENCE_CONTENT_TYPE,
    TRACEABLE_EVIDENCE_CONTRACT_VERSION,
    TRACEABLE_EVIDENCE_FIELD_ORDER,
    TRACEABLE_EVIDENCE_IDENTITY_CANONICALIZATION_VERSION,
    TRACEABLE_EVIDENCE_IDENTITY_FIELD_ORDER,
    TRACEABLE_EVIDENCE_ID_PREFIX,
    TRACEABLE_EVIDENCE_PROVENANCE_FIELD_ORDER,
    EvidenceCollection,
    EvidenceEligibilitySnapshot,
    EvidenceMaterializationContractError,
    EvidenceMaterializationIssue,
    EvidenceMaterializationIssueCode,
    EvidenceMaterializationResult,
    EvidenceMaterializationStatus,
    TraceableEvidence,
    TraceableEvidenceProvenance,
    evidence_materialization_issue,
    raise_evidence_materialization_error,
)
from .evidence_materialization_service import (
    materialize_evidence_collection,
)


__all__ = (
    "EVIDENCE_MATERIALIZATION_RESULT_CONTRACT_VERSION",
    "EVIDENCE_COLLECTION_CONTRACT_VERSION",
    "TRACEABLE_EVIDENCE_CONTRACT_VERSION",
    "EVIDENCE_ELIGIBILITY_SNAPSHOT_CONTRACT_VERSION",
    "EVIDENCE_ELIGIBILITY_SNAPSHOT_CANONICALIZATION_VERSION",
    "TRACEABLE_EVIDENCE_IDENTITY_CANONICALIZATION_VERSION",
    "EVIDENCE_COLLECTION_IDENTITY_CANONICALIZATION_VERSION",
    "TRACEABLE_EVIDENCE_CONTENT_TYPE",
    "TRACEABLE_EVIDENCE_ID_PREFIX",
    "EVIDENCE_COLLECTION_ID_PREFIX",
    "EVIDENCE_ELIGIBILITY_FIELD_ORDER",
    "TRACEABLE_EVIDENCE_PROVENANCE_FIELD_ORDER",
    "TRACEABLE_EVIDENCE_FIELD_ORDER",
    "TRACEABLE_EVIDENCE_IDENTITY_FIELD_ORDER",
    "EVIDENCE_COLLECTION_FIELD_ORDER",
    "EVIDENCE_COLLECTION_IDENTITY_FIELD_ORDER",
    "EVIDENCE_MATERIALIZATION_ISSUE_FIELD_ORDER",
    "EVIDENCE_MATERIALIZATION_RESULT_FIELD_ORDER",
    "EvidenceMaterializationStatus",
    "EvidenceMaterializationIssueCode",
    "EvidenceMaterializationIssue",
    "EvidenceMaterializationContractError",
    "EvidenceEligibilitySnapshot",
    "TraceableEvidenceProvenance",
    "TraceableEvidence",
    "EvidenceCollection",
    "EvidenceMaterializationResult",
    "evidence_materialization_issue",
    "raise_evidence_materialization_error",
    "canonicalize_evidence_eligibility_snapshot",
    "derive_evidence_eligibility_snapshot_digest",
    "canonicalize_traceable_evidence_identity",
    "derive_traceable_evidence_id",
    "canonicalize_evidence_collection_identity",
    "derive_evidence_collection_id",
    "materialize_evidence_collection",
)
